name: Build & publish drill artifacts
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Docker registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s test
      - name: Publish to DockerHub
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s jib
        env:
          GRADLE_OPTS: >
            -Djib.to.auth.username=${{ secrets.DRILL_USERNAME }}
            -Djib.to.auth.password=${{ secrets.DRILL_PASSWORD }}
